# Advance Python
# Chapter 2
## NumPy In Array creation Rution


# 1. Roution |

In [ ]:
import numpy as np


In [ ]:
# Create a array using arrange function
x = np.arange(1,17).reshape(4,4)


In [ ]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# 2. Empty (Shape,DataType)
## It creates an untitlelise array of specify shape and data type

In [ ]:
b = np.empty([3,2])

In [ ]:
b

array([[2.19662527e-315, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 4.94065646e-324]])

In [ ]:
b = np.empty([3,2],dtype=int)

In [ ]:
b

array([[          449473151,                   0],
       [8101242494674608238, 8746397786911570292],
       [7526395035267987232, 2334111870319161441]])

In [ ]:
b.ndim

2

In [ ]:
b = np.empty([3,2],dtype=str)

In [ ]:
b

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [ ]:
b.ndim

2

In [ ]:
b = np.empty([3,2],dtype=float)

In [ ]:
b

array([[2.19662527e-315, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 4.94065646e-324]])

In [ ]:
b = np.empty([3,2],dtype=set)

In [ ]:
b

array([[None, None],
       [None, None],
       [None, None]], dtype=object)

In [ ]:
b = np.empty([3,2],dtype=tuple)

In [ ]:
b

array([[None, None],
       [None, None],
       [None, None]], dtype=object)

# 3. Zeros
## It return a specifieze size

In [ ]:
c = np.zeros([4,3],dtype=float)

In [ ]:
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c.ndim

2

In [ ]:
c = np.zeros([4,3],dtype=float)

In [ ]:
c.reshape(12,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

# 4. ones
## it returns a new array of specified size and type fild with one

In [ ]:
d = np.ones(5)

In [ ]:
e = np.ones(6).reshape(3,2)

In [ ]:
e

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
e = np.ones(6,dtype=int).reshape(3,2)

In [ ]:
e

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
f = np.ones([3,2],dtype=int)

In [ ]:
f

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
s = np.ones([3,7],dtype=int)

In [ ]:
s

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

# 5. eye
## eye gives you to indentity matrix output

In [ ]:
g = np.eye(1)

In [ ]:
g

array([[1.]])

In [ ]:
h = np.eye(2)

In [ ]:
h

array([[1., 0.],
       [0., 1.]])

In [ ]:
i = np.eye(3)

In [ ]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
j = np.eye

In [ ]:
j

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)>

# 6. inspace
## it is a similarkind array creation rution to arange function. in this functio instead of stop size the number of stop size evenly space valuses between the interval is specified

In [ ]:
j = np.linspace(0,1,100)


In [ ]:
j

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
k = np.linspace(10,20,5)

In [ ]:
k

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
y = np.linspace(10,20,3, endpoint=False)

In [ ]:
y

array([10.        , 13.33333333, 16.66666667])

# **Chapeter 3: topic 1 Slicing and Indexing in array**

In [ ]:
p = np.zeros([4,3])

In [ ]:
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
p.ndim

2

In [ ]:
# i want to create two dimation array with linkspace you dont wan to hard code shape
q = np.linspace(10,30,12, endpoint=False).reshape(4,3)

In [ ]:
q

array([[10.        , 11.66666667, 13.33333333],
       [15.        , 16.66666667, 18.33333333],
       [20.        , 21.66666667, 23.33333333],
       [25.        , 26.66666667, 28.33333333]])

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a[3]

np.int64(4)

In [ ]:
a[1:4]

array([2, 3, 4])

In [ ]:
b = np.arange(1,21).reshape(4,5)

In [ ]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
b[2]

array([11, 12, 13, 14, 15])

In [ ]:
b[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
b[1:3:1,2: :1]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [ ]:
b[1:1:1,1: :1]

array([], shape=(0, 0), dtype=int64)

# **Chapter: 3 topic 2 Brodcasting of an arrary**

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a[1:4] = 95

In [ ]:
a

array([ 1, 95, 95, 95,  5])

In [ ]:
a[0] = 25

In [ ]:
a

array([25, 95, 95, 95,  5])

In [ ]:
x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])


In [ ]:
x[: :1,1:2:1] = 65

In [ ]:
x

array([[ 1, 65,  3],
       [ 4, 65,  6],
       [ 7, 65,  9]])

In [ ]:
x[0:1],x[1,2],x[2: ] = 15,35,16


In [ ]:
print(x)

[[15 15 15]
 [ 4 65 35]
 [16 16 16]]


In [ ]:
# if i wanted to create 10*10 arraay but out come need to be zeros
c = np.zeros([10,10],dtype=int)

In [ ]:
c

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
c.shape[1]

10

In [ ]:
x = np.zeros((10,10))

In [ ]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
x.shape[0]

10

In [ ]:
l = x.shape[0]

In [ ]:
for i in range(l):
  x[i] = i

In [ ]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])