## Advance Python  


## 1. Numpy
### Opration Using Numpy

In [4]:
import numpy as np


In [5]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a = np.array([[1,2,3],[4,5,6]])

In [10]:
print(a)

[[1 2 3]
 [4 5 6]]


## 2. Atributes of Numpy


## shape

In [14]:
# Return the shape of the array pf colam and rows
a.shape

(2, 3)

In [24]:
# Return the total element of the arrray
a.size

6

In [25]:
id(a)

139303550955088

## Reshape

In [26]:
#
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [33]:
a.shape = (3,2)

## Transpose
### Convers Rows in to colam and colom in to rows

In [37]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

## ndim
### Return the number of the diamention of array

In [39]:
a.ndim

2

In [40]:
f = np.array([[[1,2,3,4,5,6]]])


In [43]:
f.ndim

3

In [45]:
f

array([[[1, 2, 3, 4, 5, 6]]])

In [52]:
g = np.array([[1,2],[3,4],[5,6]])
g

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
g.shape

(3, 2)

## 3. Function of NumPy

## arange
### this is similar to the range function in python

In [64]:
a = list(range(1,11))


In [65]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [66]:
x = np.arange(1,7)


In [67]:
x

array([1, 2, 3, 4, 5, 6])

In [68]:
x = np.arange(1,7).reshape(2,3)


In [70]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
y = np.arange(7,13).reshape(2,3)

In [77]:
print(y)

[[ 7  8  9]
 [10 11 12]]


In [85]:
z = np.concatenate(x,y)

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
z = np.concatenate((x,y))

In [86]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Hstack
###

In [95]:
k = np.hstack((x,y))

In [92]:
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])